# Copy this file to /etc/modprobe.d/datadev.conf and then edit to your specific needs

### Modified Configuration to use polling instead of interrupt
### options datadev cfgTxCount=1024 cfgRxCount=1024 cfgSize=131072 cfgMode=1 cfgCont=1 cfgIrqDis=1

### Original Configuration in zip file
options datadev cfgTxCount=1024 cfgRxCount=1024 cfgSize=131072 cfgMode=1 cfgCont=1
