#!/bin/sh

set -o nounset
set -o errexit

# remove old driver
/sbin/rmmod -s datadev

# add new driver
# this is the line that needs to be tuned to the parameters of your machine
# additionally, since we reference datadev.ko from the current directory,
# we need to run this script from the directory that has datadev.ko
/sbin/insmod ./datadev.ko cfgSize=0x50000 cfgRxCount=256

# give appropriate permissions
chmod 666 /proc/datadev*
